# Reference: https://docs.codecov.io/docs/codecovyml-reference
ignore: 
  - "*Tests.swift"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
