# Reference: https://docs.codecov.io/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
github_checks:
    annotations: false
