# See the Swiftformat rule directory for longer descriptions:
# https://realm.github.io/SwiftLint/rule-directory.html

only_rules:
# --------
# All the rules below here are DEFAULT rules.
# Comments left for each disabled rule.
# --------
# - attribute_name_spacing: Swiftformat handles whitespace
  - blanket_disable_command
  - block_based_kvo
  - class_delegate_protocol
# - closing_brace: Swiftformat handles whitespace
# - closure_parameter_position: Violations of this are usually because swiftformat moved the parameters.
# - colon: Swiftformat handles whitespace
# - comma: Swiftformat handles whitespace
# - comment_spacing: Swiftformat handles whitespace
# - compiler_protocol_init: Compiler Protocol Init
  - computed_accessors_order
  - control_statement
# - custom_rules: No need for custom rules (yet) 
  - cyclomatic_complexity
  - deployment_target
  - discouraged_direct_init
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicate_imports 
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
# - file_length: Disabled due to noisiness. Baseline recording doesn't respect file_length.
  - for_where
# - force_cast: Disabled because we sometimes use a force cast for good
# - force_try: Disabled because we frequently force try in our test code.
# - function_body_length: Disabled due to noisiness. Baseline recording doesn't respect function_body_length
# - function_name_whitespace: Swiftformat handles whitespace
  - function_parameter_count
  - generic_type_name
# - identifier_name: Disabled because we're not that strict about identifier names.
  - implicit_getter
  - implicit_optional_initialization
  - inclusive_language
  - invalid_swiftlint_command
  - is_disjoint
  - large_tuple
# - leading_whitespace: Swiftformat handles whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
# - line_length: Swiftformat handles line length
  - mark
  - multiple_closures_with_trailing_closure
# - nesting: We like nested types.
  - no_fallthrough_only
  - no_space_in_method_call
  - non_optional_string_data_conversion
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nsobject_prefer_isequal
# - opening_brace: Swiftformat handles whitespace
  - optional_data_string_conversion
  - orphaned_doc_comment
  - prefer_type_checking
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_sendable
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
# - return_arrow_whitespace: Swiftformat handles whitespace
  - self_in_property_initialization
  - shorthand_operator
  - statement_position
  - static_over_final_class
  - superfluous_disable_command
# - switch_case_alignment: Swiftformat handles whitespace
  - syntactic_sugar
# - todo: We don't mind todos.
  - trailing_comma
# - trailing_newline: Swiftformat handles whitespace
  - trailing_semicolon
# - trailing_whitespace: Swiftformat handles whitespace
# - type_body_length: Disabled due to noisiness. Baseline recording doesn't respect type_body_length.
# - type_name: We're not that strict about type names.
  - unavailable_condition
  - unneeded_break_in_switch
  - unneeded_override
  - unneeded_synthesized_initializer
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
# - vertical_whitespace: Swiftformat handles whitespace
  - void_function_in_ternary
  - void_return
  - xctfail_message
# --------
# All the rules below here are OPT-IN rules.
# We haven't audited all of them, so here are just a few.
# --------
  - accessibility_trait_for_button
  - accessibility_label_for_image
  - incompatible_concurrency_annotation
  - prohibited_interface_builder
  - weak_delegate

baseline: swiftlint_baseline_12_18_25.json

excluded:
  # Autogenerated stuff
  - GraphAPI
  - Library/Strings.swift
  # Other stuff
  - Frameworks/native-secrets/ios/Secrets.swift
  - bin