// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of BlockUser
  static let BlockUserPayload = ApolloAPI.Object(
    typename: "BlockUserPayload",
    implementedInterfaces: []
  )
}