// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CancelBacking
  static let CancelBackingPayload = ApolloAPI.Object(
    typename: "CancelBackingPayload",
    implementedInterfaces: []
  )
}