// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CreatePaymentIntent
  static let CreatePaymentIntentPayload = ApolloAPI.Object(
    typename: "CreatePaymentIntentPayload",
    implementedInterfaces: []
  )
}