// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UpdateBacking
  static let UpdateBackingPayload = ApolloAPI.Object(
    typename: "UpdateBackingPayload",
    implementedInterfaces: []
  )
}