// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UpdateBackerCompleted
  static let UpdateBackerCompletedPayload = ApolloAPI.Object(
    typename: "UpdateBackerCompletedPayload",
    implementedInterfaces: []
  )
}