// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of BlockUser
public struct BlockUserInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    blockUserId: ID,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "blockUserId": blockUserId,
      "clientMutationId": clientMutationId
    ])
  }

  public var blockUserId: ID {
    get { __data["blockUserId"] }
    set { __data["blockUserId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
