// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreateAttributionEvent
public struct CreateAttributionEventInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    eventName: String,
    eventProperties: GraphQLNullable<JSON> = nil,
    projectId: GraphQLNullable<ID> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "eventName": eventName,
      "eventProperties": eventProperties,
      "projectId": projectId,
      "clientMutationId": clientMutationId
    ])
  }

  public var eventName: String {
    get { __data["eventName"] }
    set { __data["eventName"] = newValue }
  }

  public var eventProperties: GraphQLNullable<JSON> {
    get { __data["eventProperties"] }
    set { __data["eventProperties"] = newValue }
  }

  public var projectId: GraphQLNullable<ID> {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
