// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreateBacking
public struct CreateBackingInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    projectId: ID,
    amount: GraphQLNullable<String> = nil,
    locationId: GraphQLNullable<String> = nil,
    rewardId: GraphQLNullable<ID> = nil,
    rewardIds: GraphQLNullable<[ID]> = nil,
    paymentType: GraphQLNullable<String> = nil,
    refParam: GraphQLNullable<String> = nil,
    paymentSourceId: GraphQLNullable<String> = nil,
    setupIntentClientSecret: GraphQLNullable<String> = nil,
    applePay: GraphQLNullable<ApplePayInput> = nil,
    incremental: GraphQLNullable<Bool> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "projectId": projectId,
      "amount": amount,
      "locationId": locationId,
      "rewardId": rewardId,
      "rewardIds": rewardIds,
      "paymentType": paymentType,
      "refParam": refParam,
      "paymentSourceId": paymentSourceId,
      "setupIntentClientSecret": setupIntentClientSecret,
      "applePay": applePay,
      "incremental": incremental,
      "clientMutationId": clientMutationId
    ])
  }

  public var projectId: ID {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  /// Optional, will default to combined reward minimums + shipping
  public var amount: GraphQLNullable<String> {
    get { __data["amount"] }
    set { __data["amount"] = newValue }
  }

  public var locationId: GraphQLNullable<String> {
    get { __data["locationId"] }
    set { __data["locationId"] = newValue }
  }

  /// Relay encoded Reward ID - legacy - mutually exclusive with reward_ids
  public var rewardId: GraphQLNullable<ID> {
    get { __data["rewardId"] }
    set { __data["rewardId"] = newValue }
  }

  /// List of Relay encoded Reward/Add-on IDs - mutually exclusive with reward_id
  public var rewardIds: GraphQLNullable<[ID]> {
    get { __data["rewardIds"] }
    set { __data["rewardIds"] = newValue }
  }

  public var paymentType: GraphQLNullable<String> {
    get { __data["paymentType"] }
    set { __data["paymentType"] = newValue }
  }

  public var refParam: GraphQLNullable<String> {
    get { __data["refParam"] }
    set { __data["refParam"] = newValue }
  }

  public var paymentSourceId: GraphQLNullable<String> {
    get { __data["paymentSourceId"] }
    set { __data["paymentSourceId"] = newValue }
  }

  public var setupIntentClientSecret: GraphQLNullable<String> {
    get { __data["setupIntentClientSecret"] }
    set { __data["setupIntentClientSecret"] = newValue }
  }

  public var applePay: GraphQLNullable<ApplePayInput> {
    get { __data["applePay"] }
    set { __data["applePay"] = newValue }
  }

  public var incremental: GraphQLNullable<Bool> {
    get { __data["incremental"] }
    set { __data["incremental"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
