// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreateCheckout
public struct CreateCheckoutInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    projectId: ID,
    amount: GraphQLNullable<String> = nil,
    locationId: GraphQLNullable<String> = nil,
    rewardIds: GraphQLNullable<[ID]> = nil,
    refParam: GraphQLNullable<String> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "projectId": projectId,
      "amount": amount,
      "locationId": locationId,
      "rewardIds": rewardIds,
      "refParam": refParam,
      "clientMutationId": clientMutationId
    ])
  }

  public var projectId: ID {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  public var amount: GraphQLNullable<String> {
    get { __data["amount"] }
    set { __data["amount"] = newValue }
  }

  public var locationId: GraphQLNullable<String> {
    get { __data["locationId"] }
    set { __data["locationId"] = newValue }
  }

  public var rewardIds: GraphQLNullable<[ID]> {
    get { __data["rewardIds"] }
    set { __data["rewardIds"] = newValue }
  }

  public var refParam: GraphQLNullable<String> {
    get { __data["refParam"] }
    set { __data["refParam"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
