// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreateFlagging
public struct CreateFlaggingInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    contentId: ID,
    kind: GraphQLEnum<NonDeprecatedFlaggingKind>,
    details: GraphQLNullable<String> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "contentId": contentId,
      "kind": kind,
      "details": details,
      "clientMutationId": clientMutationId
    ])
  }

  public var contentId: ID {
    get { __data["contentId"] }
    set { __data["contentId"] = newValue }
  }

  public var kind: GraphQLEnum<NonDeprecatedFlaggingKind> {
    get { __data["kind"] }
    set { __data["kind"] = newValue }
  }

  public var details: GraphQLNullable<String> {
    get { __data["details"] }
    set { __data["details"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
