// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreatePaymentSource
public struct CreatePaymentSourceInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    paymentType: GraphQLNullable<GraphQLEnum<PaymentTypes>> = nil,
    stripeToken: GraphQLNullable<String> = nil,
    stripeCardId: GraphQLNullable<String> = nil,
    reusable: GraphQLNullable<Bool> = nil,
    intentClientSecret: GraphQLNullable<String> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "paymentType": paymentType,
      "stripeToken": stripeToken,
      "stripeCardId": stripeCardId,
      "reusable": reusable,
      "intentClientSecret": intentClientSecret,
      "clientMutationId": clientMutationId
    ])
  }

  public var paymentType: GraphQLNullable<GraphQLEnum<PaymentTypes>> {
    get { __data["paymentType"] }
    set { __data["paymentType"] = newValue }
  }

  public var stripeToken: GraphQLNullable<String> {
    get { __data["stripeToken"] }
    set { __data["stripeToken"] = newValue }
  }

  public var stripeCardId: GraphQLNullable<String> {
    get { __data["stripeCardId"] }
    set { __data["stripeCardId"] = newValue }
  }

  public var reusable: GraphQLNullable<Bool> {
    get { __data["reusable"] }
    set { __data["reusable"] = newValue }
  }

  public var intentClientSecret: GraphQLNullable<String> {
    get { __data["intentClientSecret"] }
    set { __data["intentClientSecret"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
