// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of SignInWithApple
public struct SignInWithAppleInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    firstName: GraphQLNullable<String> = nil,
    lastName: GraphQLNullable<String> = nil,
    authCode: String,
    iosAppId: String,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "firstName": firstName,
      "lastName": lastName,
      "authCode": authCode,
      "iosAppId": iosAppId,
      "clientMutationId": clientMutationId
    ])
  }

  public var firstName: GraphQLNullable<String> {
    get { __data["firstName"] }
    set { __data["firstName"] = newValue }
  }

  public var lastName: GraphQLNullable<String> {
    get { __data["lastName"] }
    set { __data["lastName"] = newValue }
  }

  public var authCode: String {
    get { __data["authCode"] }
    set { __data["authCode"] = newValue }
  }

  public var iosAppId: String {
    get { __data["iosAppId"] }
    set { __data["iosAppId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
