// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of TriggerThirdPartyEvent
public struct TriggerThirdPartyEventInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    deviceId: String,
    eventName: String,
    firebaseScreen: GraphQLNullable<String> = nil,
    firebasePreviousScreen: GraphQLNullable<String> = nil,
    items: GraphQLNullable<[ThirdPartyEventItemInput]> = nil,
    projectId: ID,
    pledgeAmount: GraphQLNullable<Double> = nil,
    shipping: GraphQLNullable<Double> = nil,
    transactionId: GraphQLNullable<String> = nil,
    userId: GraphQLNullable<String> = nil,
    appData: GraphQLNullable<AppDataInput> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "deviceId": deviceId,
      "eventName": eventName,
      "firebaseScreen": firebaseScreen,
      "firebasePreviousScreen": firebasePreviousScreen,
      "items": items,
      "projectId": projectId,
      "pledgeAmount": pledgeAmount,
      "shipping": shipping,
      "transactionId": transactionId,
      "userId": userId,
      "appData": appData,
      "clientMutationId": clientMutationId
    ])
  }

  public var deviceId: String {
    get { __data["deviceId"] }
    set { __data["deviceId"] = newValue }
  }

  public var eventName: String {
    get { __data["eventName"] }
    set { __data["eventName"] = newValue }
  }

  public var firebaseScreen: GraphQLNullable<String> {
    get { __data["firebaseScreen"] }
    set { __data["firebaseScreen"] = newValue }
  }

  public var firebasePreviousScreen: GraphQLNullable<String> {
    get { __data["firebasePreviousScreen"] }
    set { __data["firebasePreviousScreen"] = newValue }
  }

  public var items: GraphQLNullable<[ThirdPartyEventItemInput]> {
    get { __data["items"] }
    set { __data["items"] = newValue }
  }

  public var projectId: ID {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  public var pledgeAmount: GraphQLNullable<Double> {
    get { __data["pledgeAmount"] }
    set { __data["pledgeAmount"] = newValue }
  }

  public var shipping: GraphQLNullable<Double> {
    get { __data["shipping"] }
    set { __data["shipping"] = newValue }
  }

  public var transactionId: GraphQLNullable<String> {
    get { __data["transactionId"] }
    set { __data["transactionId"] = newValue }
  }

  public var userId: GraphQLNullable<String> {
    get { __data["userId"] }
    set { __data["userId"] = newValue }
  }

  public var appData: GraphQLNullable<AppDataInput> {
    get { __data["appData"] }
    set { __data["appData"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
