// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of UpdateBacking
public struct UpdateBackingInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    id: ID,
    amount: GraphQLNullable<String> = nil,
    rewardId: GraphQLNullable<ID> = nil,
    rewardIds: GraphQLNullable<[ID]> = nil,
    locationId: GraphQLNullable<String> = nil,
    paymentSourceId: GraphQLNullable<String> = nil,
    intentClientSecret: GraphQLNullable<String> = nil,
    applePay: GraphQLNullable<ApplePayInput> = nil,
    incremental: GraphQLNullable<Bool> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "id": id,
      "amount": amount,
      "rewardId": rewardId,
      "rewardIds": rewardIds,
      "locationId": locationId,
      "paymentSourceId": paymentSourceId,
      "intentClientSecret": intentClientSecret,
      "applePay": applePay,
      "incremental": incremental,
      "clientMutationId": clientMutationId
    ])
  }

  public var id: ID {
    get { __data["id"] }
    set { __data["id"] = newValue }
  }

  public var amount: GraphQLNullable<String> {
    get { __data["amount"] }
    set { __data["amount"] = newValue }
  }

  /// Relay encoded Reward ID - legacy
  public var rewardId: GraphQLNullable<ID> {
    get { __data["rewardId"] }
    set { __data["rewardId"] = newValue }
  }

  /// List of Relay encoded Reward/Add-on IDs
  public var rewardIds: GraphQLNullable<[ID]> {
    get { __data["rewardIds"] }
    set { __data["rewardIds"] = newValue }
  }

  public var locationId: GraphQLNullable<String> {
    get { __data["locationId"] }
    set { __data["locationId"] = newValue }
  }

  /// new payment source id
  public var paymentSourceId: GraphQLNullable<String> {
    get { __data["paymentSourceId"] }
    set { __data["paymentSourceId"] = newValue }
  }

  /// Stripe SetupIntent client secret
  public var intentClientSecret: GraphQLNullable<String> {
    get { __data["intentClientSecret"] }
    set { __data["intentClientSecret"] = newValue }
  }

  public var applePay: GraphQLNullable<ApplePayInput> {
    get { __data["applePay"] }
    set { __data["applePay"] = newValue }
  }

  public var incremental: GraphQLNullable<Bool> {
    get { __data["incremental"] }
    set { __data["incremental"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
