// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of UpdateUserAccount
public struct UpdateUserAccountInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    currentPassword: GraphQLNullable<String> = nil,
    password: GraphQLNullable<String> = nil,
    passwordConfirmation: GraphQLNullable<String> = nil,
    email: GraphQLNullable<Email> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "currentPassword": currentPassword,
      "password": password,
      "passwordConfirmation": passwordConfirmation,
      "email": email,
      "clientMutationId": clientMutationId
    ])
  }

  public var currentPassword: GraphQLNullable<String> {
    get { __data["currentPassword"] }
    set { __data["currentPassword"] = newValue }
  }

  public var password: GraphQLNullable<String> {
    get { __data["password"] }
    set { __data["password"] = newValue }
  }

  public var passwordConfirmation: GraphQLNullable<String> {
    get { __data["passwordConfirmation"] }
    set { __data["passwordConfirmation"] = newValue }
  }

  public var email: GraphQLNullable<Email> {
    get { __data["email"] }
    set { __data["email"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
