// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of UpdateUserProfile
public struct UpdateUserProfileInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    name: GraphQLNullable<String> = nil,
    biography: GraphQLNullable<String> = nil,
    locationId: GraphQLNullable<ID> = nil,
    chosenCurrency: GraphQLNullable<GraphQLEnum<CurrencyCode>> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "name": name,
      "biography": biography,
      "locationId": locationId,
      "chosenCurrency": chosenCurrency,
      "clientMutationId": clientMutationId
    ])
  }

  public var name: GraphQLNullable<String> {
    get { __data["name"] }
    set { __data["name"] = newValue }
  }

  public var biography: GraphQLNullable<String> {
    get { __data["biography"] }
    set { __data["biography"] = newValue }
  }

  public var locationId: GraphQLNullable<ID> {
    get { __data["locationId"] }
    set { __data["locationId"] = newValue }
  }

  public var chosenCurrency: GraphQLNullable<GraphQLEnum<CurrencyCode>> {
    get { __data["chosenCurrency"] }
    set { __data["chosenCurrency"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
