// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of AddUserToSecretRewardGroup
  static let AddUserToSecretRewardGroupPayload = ApolloAPI.Object(
    typename: "AddUserToSecretRewardGroupPayload",
    implementedInterfaces: []
  )
}