// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of ClearUserUnseenActivity
  static let ClearUserUnseenActivityPayload = ApolloAPI.Object(
    typename: "ClearUserUnseenActivityPayload",
    implementedInterfaces: []
  )
}