// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of CompleteOnSessionCheckout
  static let CompleteOnSessionCheckoutPayload = ApolloAPI.Object(
    typename: "CompleteOnSessionCheckoutPayload",
    implementedInterfaces: []
  )
}