// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CreateSetupIntent
  static let CreateSetupIntentPayload = ApolloAPI.Object(
    typename: "CreateSetupIntentPayload",
    implementedInterfaces: []
  )
}