// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of CreatePaymentSource
  static let CreatePaymentSourcePayload = ApolloAPI.Object(
    typename: "CreatePaymentSourcePayload",
    implementedInterfaces: []
  )
}