// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of CreateOrUpdateBackingAddress
  static let CreateOrUpdateBackingAddressPayload = ApolloAPI.Object(
    typename: "CreateOrUpdateBackingAddressPayload",
    implementedInterfaces: []
  )
}