// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of CreateAttributionEvent
  static let CreateAttributionEventPayload = ApolloAPI.Object(
    typename: "CreateAttributionEventPayload",
    implementedInterfaces: []
  )
}