// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of CreateCheckout
  static let CreateCheckoutPayload = ApolloAPI.Object(
    typename: "CreateCheckoutPayload",
    implementedInterfaces: []
  )
}