// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CreateBacking
  static let CreateBackingPayload = ApolloAPI.Object(
    typename: "CreateBackingPayload",
    implementedInterfaces: []
  )
}