// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of CreateFlagging
  static let CreateFlaggingPayload = ApolloAPI.Object(
    typename: "CreateFlaggingPayload",
    implementedInterfaces: []
  )
}