// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of PaymentSourceDelete
  static let PaymentSourceDeletePayload = ApolloAPI.Object(
    typename: "PaymentSourceDeletePayload",
    implementedInterfaces: []
  )
}