// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of PostComment
  static let PostCommentPayload = ApolloAPI.Object(
    typename: "PostCommentPayload",
    implementedInterfaces: []
  )
}