// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of SignInWithApple
  static let SignInWithApplePayload = ApolloAPI.Object(
    typename: "SignInWithApplePayload",
    implementedInterfaces: []
  )
}