// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TriggerThirdPartyEvent
  static let TriggerThirdPartyEventPayload = ApolloAPI.Object(
    typename: "TriggerThirdPartyEventPayload",
    implementedInterfaces: []
  )
}