// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UnwatchProject
  static let UnwatchProjectPayload = ApolloAPI.Object(
    typename: "UnwatchProjectPayload",
    implementedInterfaces: []
  )
}