// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of UpdateUserProfile
  static let UpdateUserProfilePayload = ApolloAPI.Object(
    typename: "UpdateUserProfilePayload",
    implementedInterfaces: []
  )
}