// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension GraphAPI.Objects {
  /// Autogenerated return type of UpdateUserAccount
  static let UpdateUserAccountPayload = ApolloAPI.Object(
    typename: "UpdateUserAccountPayload",
    implementedInterfaces: []
  )
}