// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UserSendEmailVerification
  static let UserSendEmailVerificationPayload = ApolloAPI.Object(
    typename: "UserSendEmailVerificationPayload",
    implementedInterfaces: []
  )
}