// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of WatchProject
  static let WatchProjectPayload = ApolloAPI.Object(
    typename: "WatchProjectPayload",
    implementedInterfaces: []
  )
}