// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of AddUserToSecretRewardGroup
public struct AddUserToSecretRewardGroupInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    secretRewardToken: String,
    projectId: GraphQLNullable<ID> = nil,
    pid: GraphQLNullable<Int> = nil,
    slug: GraphQLNullable<String> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "secretRewardToken": secretRewardToken,
      "projectId": projectId,
      "pid": pid,
      "slug": slug,
      "clientMutationId": clientMutationId
    ])
  }

  /// Secret reward token shared by the creator
  public var secretRewardToken: String {
    get { __data["secretRewardToken"] }
    set { __data["secretRewardToken"] = newValue }
  }

  /// ID of the project with secret rewards
  public var projectId: GraphQLNullable<ID> {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  /// Project ID of the project with secret rewards
  public var pid: GraphQLNullable<Int> {
    get { __data["pid"] }
    set { __data["pid"] = newValue }
  }

  /// Slug of the project with secret rewards
  public var slug: GraphQLNullable<String> {
    get { __data["slug"] }
    set { __data["slug"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
