// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of AddUserToSecretRewardGroup
public struct AddUserToSecretRewardGroupInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    projectId: ID,
    secretRewardToken: String,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "projectId": projectId,
      "secretRewardToken": secretRewardToken,
      "clientMutationId": clientMutationId
    ])
  }

  /// ID of the project with secret rewards
  public var projectId: ID {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  /// Secret reward token shared by the creator
  public var secretRewardToken: String {
    get { __data["secretRewardToken"] }
    set { __data["secretRewardToken"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
