// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CancelBacking
public struct CancelBackingInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    id: ID,
    note: GraphQLNullable<String> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "id": id,
      "note": note,
      "clientMutationId": clientMutationId
    ])
  }

  /// ID of the backing being canceled
  public var id: ID {
    get { __data["id"] }
    set { __data["id"] = newValue }
  }

  /// Optional cancellation note
  public var note: GraphQLNullable<String> {
    get { __data["note"] }
    set { __data["note"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
