// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CompleteOnSessionCheckout
public struct CompleteOnSessionCheckoutInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    checkoutId: ID,
    paymentIntentClientSecret: String,
    paymentSourceId: GraphQLNullable<String> = nil,
    paymentSourceReusable: GraphQLNullable<Bool> = nil,
    applePay: GraphQLNullable<ApplePayInput> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "checkoutId": checkoutId,
      "paymentIntentClientSecret": paymentIntentClientSecret,
      "paymentSourceId": paymentSourceId,
      "paymentSourceReusable": paymentSourceReusable,
      "applePay": applePay,
      "clientMutationId": clientMutationId
    ])
  }

  /// The graphql relay id of the checkout (base64 encoded)
  public var checkoutId: ID {
    get { __data["checkoutId"] }
    set { __data["checkoutId"] = newValue }
  }

  /// the client_secret returned by createPaymentIntent, starts with `pi_` (the same secret passed to stripe)
  public var paymentIntentClientSecret: String {
    get { __data["paymentIntentClientSecret"] }
    set { __data["paymentIntentClientSecret"] = newValue }
  }

  /// Kickstarter internal payment source id. Expects a number (not the stripe id starting with `pm_`). Pass in when using a saved card (optional)
  public var paymentSourceId: GraphQLNullable<String> {
    get { __data["paymentSourceId"] }
    set { __data["paymentSourceId"] = newValue }
  }

  /// If the payment source can be reused for future payments (optional)
  public var paymentSourceReusable: GraphQLNullable<Bool> {
    get { __data["paymentSourceReusable"] }
    set { __data["paymentSourceReusable"] = newValue }
  }

  /// Apple pay attributes for creating a payment source (optional)
  public var applePay: GraphQLNullable<ApplePayInput> {
    get { __data["applePay"] }
    set { __data["applePay"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
