// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreateSetupIntent
public struct CreateSetupIntentInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    setupIntentContext: GraphQLNullable<GraphQLEnum<StripeIntentContextTypes>> = nil,
    projectId: GraphQLNullable<ID> = nil,
    sepaEligible: GraphQLNullable<Bool> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "setupIntentContext": setupIntentContext,
      "projectId": projectId,
      "sepaEligible": sepaEligible,
      "clientMutationId": clientMutationId
    ])
  }

  /// Context in which this stripe intent is created
  public var setupIntentContext: GraphQLNullable<GraphQLEnum<StripeIntentContextTypes>> {
    get { __data["setupIntentContext"] }
    set { __data["setupIntentContext"] = newValue }
  }

  public var projectId: GraphQLNullable<ID> {
    get { __data["projectId"] }
    set { __data["projectId"] = newValue }
  }

  /// If sepa should be added to the payment method types
  public var sepaEligible: GraphQLNullable<Bool> {
    get { __data["sepaEligible"] }
    set { __data["sepaEligible"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
