// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of CreateOrUpdateBackingAddress
public struct CreateOrUpdateBackingAddressInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    backingId: ID,
    addressId: ID,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "backingId": backingId,
      "addressId": addressId,
      "clientMutationId": clientMutationId
    ])
  }

  public var backingId: ID {
    get { __data["backingId"] }
    set { __data["backingId"] = newValue }
  }

  public var addressId: ID {
    get { __data["addressId"] }
    set { __data["addressId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
