// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of PaymentSourceDelete
public struct PaymentSourceDeleteInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    paymentSourceId: String,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "paymentSourceId": paymentSourceId,
      "clientMutationId": clientMutationId
    ])
  }

  public var paymentSourceId: String {
    get { __data["paymentSourceId"] }
    set { __data["paymentSourceId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
