// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of PostComment
public struct PostCommentInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    commentableId: ID,
    body: String,
    parentId: GraphQLNullable<ID> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "commentableId": commentableId,
      "body": body,
      "parentId": parentId,
      "clientMutationId": clientMutationId
    ])
  }

  /// The ID of the object you are commenting on
  public var commentableId: ID {
    get { __data["commentableId"] }
    set { __data["commentableId"] = newValue }
  }

  /// The body of the comment
  public var body: String {
    get { __data["body"] }
    set { __data["body"] = newValue }
  }

  /// The ID of the comment you are replying to
  public var parentId: GraphQLNullable<ID> {
    get { __data["parentId"] }
    set { __data["parentId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
