// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of WatchProject
public struct WatchProjectInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    id: ID,
    trackingContext: GraphQLNullable<String> = nil,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "id": id,
      "trackingContext": trackingContext,
      "clientMutationId": clientMutationId
    ])
  }

  public var id: ID {
    get { __data["id"] }
    set { __data["id"] = newValue }
  }

  public var trackingContext: GraphQLNullable<String> {
    get { __data["trackingContext"] }
    set { __data["trackingContext"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
