fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    xcversion(version: "8.3.3")
  end

  ### BETA

  desc "Build Beta"
  lane :beta_gym do
    build_app(
      output_name: "KickBeta",
      export_method: "enterprise",
      configuration: "Hockey Beta"
    )
  end

  desc "Upload Beta to HockeyApp"
  lane :beta_hockey do
    upload_hockey(
      ipa: "KickBeta.ipa",
      dsym: "KickBeta.app.dSYM.zip",
      public_identifier: ENV["HOCKEY_BETA_APP_ID"]
    )
  end

  ### PRODUCTION

  desc "Build Production"
  lane :itunes_gym do
    build_app(
      output_name: "Kickstarter",
      export_method: "app-store",
      configuration: "Release"
    )
  end

  desc "Upload Production to HockeyApp"
  lane :itunes_hockey do
    upload_hockey(
      ipa: "Kickstarter.ipa",
      dsym: "Kickstarter.app.dSYM.zip",
      public_identifier: ENV["HOCKEY_RELEASE_APP_ID"]
    )
  end

  desc "Upload to the app store"
  lane :itunes_deliver do

    deliver(
      force: true,
      username: ENV["ITUNES_CONNECT_ACCOUNT"],
      app_identifier: ENV["ITUNES_APP_IDENTIFIER"],
      app: ENV["ITUNES_APP_ID"],
      ipa: "Kickstarter.ipa",
      team_id: ENV["ITUNES_TEAM_ID"],
      skip_screenshots: true,
      skip_metadata: true
    )

    slack(
      slack_url: ENV["SLACK_WEBHOOK"],
      message: "Successfully uploaded" +
        " v" + get_version_number(xcodeproj: "Kickstarter.xcodeproj") +
        " (" + get_build_number(xcodeproj: "Kickstarter.xcodeproj") + ")" +
        " of the Kickstarter iOS app to iTunes Connect 🚀"
    )
  end

  ### ALPHA

  desc "Build Alpha"
  lane :alpha_gym do
    build_app(
      output_name: "KickAlpha",
      export_method: "enterprise",
      configuration: "Hockey Alpha"
    )
  end

  desc "Upload Alpha to HockeyApp"
  lane :alpha_hockey do
    upload_hockey(
      ipa: "KickAlpha.ipa",
      dsym: "KickAlpha.app.dSYM.zip",
      public_identifier: ENV["HOCKEY_ALPHA_APP_ID"]
    )
  end

  ### SHARED

  private_lane :build_app do |options|
    gym(
      output_name: options[:output_name],
      export_method: options[:export_method],
      scheme: "Kickstarter-iOS",
      configuration: options[:configuration]
    )
  end

  private_lane :upload_hockey do |options|
    hockey(
      api_token: ENV["HOCKEY_APP_TOKEN"],
      ipa: options[:ipa],
      dsym: options[:dsym],
      public_identifier: options[:public_identifier],
      repository_url: ENV["CIRCLE_REPOSITORY_URL"],
      build_server_url: ENV["CIRCLE_BUILD_URL"],
      commit_sha: ENV["CIRCLE_SHA1"],
      notes: "CircleCI build " + ENV["CIRCLE_BUILD_NUM"],
      bypass_cdn: true,
      notify: "1"
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
